# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Mon Feb  8 08:37:47 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(QtGui.QMainWindow):
    def __init__(self):
        QtGui.QMainWindow.__init__(self)
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(597, 250)
        MainWindow.setMinimumSize(QtCore.QSize(597, 250))
        MainWindow.setMaximumSize(QtCore.QSize(597, 250))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 581, 201))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lableoffen = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lableoffen.setFont(font)
        self.lableoffen.setObjectName("lableoffen")
        self.verticalLayout.addWidget(self.lableoffen)
        self.lablekorrekt = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lablekorrekt.setFont(font)
        self.lablekorrekt.setObjectName("lablekorrekt")
        self.verticalLayout.addWidget(self.lablekorrekt)
        self.lablefalsch = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lablefalsch.setFont(font)
        self.lablefalsch.setObjectName("lablefalsch")
        self.verticalLayout.addWidget(self.lablefalsch)
        self.lablegesamt = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lablegesamt.setFont(font)
        self.lablegesamt.setObjectName("lablegesamt")
        self.verticalLayout.addWidget(self.lablegesamt)
        self.lablespiele = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.lablespiele.setFont(font)
        self.lablespiele.setObjectName("lablespiele")
        self.verticalLayout.addWidget(self.lablespiele)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.zahloffen = QtGui.QLabel(self.horizontalLayoutWidget)
        self.zahloffen.setObjectName("zahloffen")
        self.verticalLayout_2.addWidget(self.zahloffen)
        self.zahlkorrekt = QtGui.QLabel(self.horizontalLayoutWidget)
        self.zahlkorrekt.setObjectName("zahlkorrekt")
        self.verticalLayout_2.addWidget(self.zahlkorrekt)
        self.zahlfalsch = QtGui.QLabel(self.horizontalLayoutWidget)
        self.zahlfalsch.setObjectName("zahlfalsch")
        self.verticalLayout_2.addWidget(self.zahlfalsch)
        self.zahlgesamt = QtGui.QLabel(self.horizontalLayoutWidget)
        self.zahlgesamt.setObjectName("zahlgesamt")
        self.verticalLayout_2.addWidget(self.zahlgesamt)
        self.zahlspiele = QtGui.QLabel(self.horizontalLayoutWidget)
        self.zahlspiele.setObjectName("zahlspiele")
        self.verticalLayout_2.addWidget(self.zahlspiele)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_11 = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.b1 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b1.setObjectName("b1")
        self.horizontalLayout_2.addWidget(self.b1)
        self.b2 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b2.setObjectName("b2")
        self.horizontalLayout_2.addWidget(self.b2)
        self.b3 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b3.setObjectName("b3")
        self.horizontalLayout_2.addWidget(self.b3)
        self.b4 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b4.setObjectName("b4")
        self.horizontalLayout_2.addWidget(self.b4)
        self.b5 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b5.setObjectName("b5")
        self.horizontalLayout_2.addWidget(self.b5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.b6 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b6.setObjectName("b6")
        self.horizontalLayout_3.addWidget(self.b6)
        self.b7 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b7.setObjectName("b7")
        self.horizontalLayout_3.addWidget(self.b7)
        self.b8 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b8.setObjectName("b8")
        self.horizontalLayout_3.addWidget(self.b8)
        self.b9 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b9.setObjectName("b9")
        self.horizontalLayout_3.addWidget(self.b9)
        self.b10 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b10.setObjectName("b10")
        self.horizontalLayout_3.addWidget(self.b10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.b11 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b11.setObjectName("b11")
        self.horizontalLayout_4.addWidget(self.b11)
        self.b12 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b12.setObjectName("b12")
        self.horizontalLayout_4.addWidget(self.b12)
        self.b13 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b13.setObjectName("b13")
        self.horizontalLayout_4.addWidget(self.b13)
        self.b14 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b14.setObjectName("b14")
        self.horizontalLayout_4.addWidget(self.b14)
        self.b15 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.b15.setObjectName("b15")
        self.horizontalLayout_4.addWidget(self.b15)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bneu = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.bneu.setObjectName("bneu")
        self.horizontalLayout_5.addWidget(self.bneu)
        self.bend = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.bend.setObjectName("bend")
        self.horizontalLayout_5.addWidget(self.bend)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 597, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.lableoffen.setText(QtGui.QApplication.translate("MainWindow", "offen:", None, QtGui.QApplication.UnicodeUTF8))
        self.lablekorrekt.setText(QtGui.QApplication.translate("MainWindow", "korrekt:", None, QtGui.QApplication.UnicodeUTF8))
        self.lablefalsch.setText(QtGui.QApplication.translate("MainWindow", "falsch:", None, QtGui.QApplication.UnicodeUTF8))
        self.lablegesamt.setText(QtGui.QApplication.translate("MainWindow", "gesamt:", None, QtGui.QApplication.UnicodeUTF8))
        self.lablespiele.setText(QtGui.QApplication.translate("MainWindow", "Spiele", None, QtGui.QApplication.UnicodeUTF8))
        self.zahloffen.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.zahlkorrekt.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.zahlfalsch.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.zahlgesamt.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.zahlspiele.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Druck die Buttons in aufsteigender Richtung!", None, QtGui.QApplication.UnicodeUTF8))
        self.b1.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.b2.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.b3.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.b4.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.b5.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.b6.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.b7.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.b8.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.b9.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.b10.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.b11.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.b12.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.b13.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.b14.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.b15.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.bneu.setText(QtGui.QApplication.translate("MainWindow", "Neu", None, QtGui.QApplication.UnicodeUTF8))
        self.bend.setText(QtGui.QApplication.translate("MainWindow", "Ende", None, QtGui.QApplication.UnicodeUTF8))


